---
language: python
services: docker

env:
  global:
    - ROLE_NAME: docker-grafana
  matix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8

before_install:
  # Make sure everything's up to date
  - sudo apt-get update -qq

install:
  # Install test dependencies
  - pip install molecule docker

before_script:
  # Use Actual ansible role galaxy name for the project directory
  - cd ../
  - mv ansible-role-$ROLE_NAME ppadial.$ROLE_NAME
  - cd ppadial.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  