---
# tasks file for docker
# Install aptitude, which is preferred by Ansible as an alternative to the apt package manager.
- name: Install aptitude using apt
  apt: name=aptitude state=present update_cache=yes force_apt_get=yes
  register: result

# Based on https://docs.docker.com/engine/installation/linux/ubuntu/
- name: Ensure old versions of Docker are not installed.
  apt: name={{ item }} state=absent
  loop: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']

- name: Install required system packages
  apt: name={{ item }} state=present update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python-pip', 'python-setuptools', 'virtualenv' ]
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Install Docker
  apt: name={{ item }} state=present update_cache=yes
  loop: [ 'docker', 'docker-compose' ]
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Install Docker Module for Python
  pip:
    name:
    - docker
    - jmespath
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Add user to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
